### ISSUE TITLE
All the different mood blob effects actually set the "Blue Mood Blobs" effect

### ISSUE THREAD

**Issue by jghaanstra** [WeeJeWel/net.weejewel.hyperion#1]
Great app but I noticed a minor issue with the set effect action card.

When selecting one of the Mood Blobs effects they all set the "Blue mood blobs" effect instead of the selected effect. All other selected effects do actually show the selected effects.

**Comment by WeeJeWel** [comment]
Fixed. It seemed that args was actually an important parameter. I assumed it just were the default arguments. :)
