### ISSUE TITLE
App crashes since 2.0.0

### ISSUE THREAD

**Issue by jghaanstra** [WeeJeWel/net.weejewel.hyperion#3]
**What is your Homey version (Settings → System)?**
firmware 0.9.3 / app 2.0.0

**What did you try to achieve?**
Do stuff using the app. I have a flow that changes the effect of Hyperion.

**Please include detailed steps how we can reproduce the issue**
Just try to do stuff and eventually the app crashes. It does not always do this but over time it will.

**What was the result?**
A crashed app with the following stacktrace.

```
Stack trace:

TypeError: Cannot read property 'effects' of undefined
at Object.self.capabilities.hyperion_effect.set (/drivers/hyperion/driver.js:176:25)
at Object.<anonymous> (/drivers/hyperion/driver.js:14:37)
at emitThree (events.js:97:13)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:1:211
at /homey-app/helpers/client.js:1:1013
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:982)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)

Exit code: 1
```

**What did you expect as result?**
A working app.

**Comment by jghaanstra** [comment]
Edited the original post, now it still crashed from time to time but I get a proper stacktrace which I have added to the original bug post.

It also seems to happen more often.

**Comment by jghaanstra** [comment]
Ok, this happens when the RPi that runs Hyperion is not powered on and a flow is triggered that contains a card to set an effect. I only have Hyperion running in the evening but also have a flow that sets the knight rider effect when my doorbell is rang. So if this happens during the day the Hyperion app crashes.

**Comment by WeeJeWel** [comment]
Great find! I'll update it ASAP

**Comment by WeeJeWel** [comment]
Fixed :)
