### ISSUE TITLE
Card pulldown menu shows message "missing_listener"

### ISSUE THREAD

**Issue by jghaanstra** [WeeJeWel/net.weejewel.hyperion#4]
**What is your Homey version (Settings → System)?**
0.10.0

**What did you try to achieve?**
Add a card to change the Hyperion effect. When trying to select an effect I dont see the available effects but an error message "missing_listener".

**Please include detailed steps how we can reproduce the issue**
Just try to select an effect on the show an effect card on firmware 0.10.0.

**What was the result?**
An error and not being able to use the app,

**What did you expect as result?**
Being able to select an effect.

**Any other remarks**
Seems to be a generic problem as this also happens on the Harmony Hub app.

**Comment by WeeJeWel** [comment]
Fixed in Homey 0.10.1
