### ISSUE TITLE
Error when selecting effect in flow

### ISSUE THREAD

**Issue by Fire69** [WeeJeWel/net.weejewel.hyperion#9]
Hi,

I just tried changing an Hyperion effect in a flow.  This is what I got:
![image](https://user-images.githubusercontent.com/1757287/37170411-06de7ace-230b-11e8-85d3-06144d48d24f.png)

When I check my Hyperion in Devices, everything is working OK.
![image](https://user-images.githubusercontent.com/1757287/37170437-1936ef94-230b-11e8-8a58-a013b90fdedf.png)

I tried creating a new device, same problem occurs.

**Comment by Fire69** [comment]
Any chance this is getting an update? :(

**Comment by WeeJeWel** [comment]
I don't have a Hyperion installation anymore so probably not. If anyone wants to take ownership of the project i'd be more than happy!

**Comment by Fire69** [comment]
No way you might be able to easily fix this with your programming superpowers if I send you a log? ;-)
Since the device is working just fine the connection to Hyperion is working correctly (colors and effects can be selected), so it's a (small? :-) ) problem with the card in the flow probably.

**Comment by WeeJeWel** [comment]
Could you create a screenshot of the Inspector open when typing, then hit the Network tab, click the red request and show the 'response body' (Should be some JSON with an error message).

**Comment by Fire69** [comment]
Thanks for taking the time :-)
Not entirely sure it it's this you want?
![image](https://user-images.githubusercontent.com/1757287/41342214-01a23d1a-6efc-11e8-9dca-b60a3c7250f6.png)
The moment I select the card it shows the device-error in the card, I don't have to type anything.

**Comment by WeeJeWel** [comment]
Could you try to remove and add the card in the Flow again? Be sure to use the Homey Desktop App, I think there's a bug in the smartphone app preview when saving flows with devices.

**Comment by Fire69** [comment]
Using the desktop app, I removed the card from the flow, deleted the device and then uninstalled the app.
After that I started from zero => app, device, flow.
Same error :(

**Comment by WeeJeWel** [comment]
Thank you! This is most likely a bug in Homey itself and I'm pretty sure it has been fixed in Homey v2.0

**Comment by Fire69** [comment]
Not trying to be negative or anything here, but... 2.0? That's not going to be released for quite some time, right?

**Comment by WeeJeWel** [comment]
I understand your concern. It's close enough however to not fix issues like these in 1.x anymore.

**Comment by Fire69** [comment]
Ok, I'll try to be positive then and wait it out ;-)
